# Generated by Django 2.2.6 on 2019-11-22 14:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='media')),
                ('post_title', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_auther', models.CharField(max_length=100)),
                ('post_content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
