# Generated by Django 2.2.6 on 2019-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191123_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
