# Generated by Django 2.2.6 on 2019-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20191130_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.TextField(),
        ),
    ]
